// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_drug_use_app/test/providers/daily_checkin_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_drug_use_app/models/daily_checkin_model.dart' as _i4;
import 'package:mobile_drug_use_app/features/daily_chekin/services/daily_checkin_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DailyCheckinRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyCheckinRepository extends _i1.Mock
    implements _i2.DailyCheckinRepository {
  MockDailyCheckinRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveCheckin(_i4.DailyCheckin? checkin) =>
      (super.noSuchMethod(
            Invocation.method(#saveCheckin, [checkin]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCheckin(String? id, _i4.DailyCheckin? checkin) =>
      (super.noSuchMethod(
            Invocation.method(#updateCheckin, [id, checkin]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DailyCheckin>> fetchCheckinsByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCheckinsByDate, [date]),
            returnValue: _i3.Future<List<_i4.DailyCheckin>>.value(
              <_i4.DailyCheckin>[],
            ),
          )
          as _i3.Future<List<_i4.DailyCheckin>>);

  @override
  _i3.Future<List<_i4.DailyCheckin>> fetchCheckinsInRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCheckinsInRange, [startDate, endDate]),
            returnValue: _i3.Future<List<_i4.DailyCheckin>>.value(
              <_i4.DailyCheckin>[],
            ),
          )
          as _i3.Future<List<_i4.DailyCheckin>>);

  @override
  _i3.Future<_i4.DailyCheckin?> fetchCheckinByDateAndTime(
    DateTime? date,
    String? timeOfDay,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCheckinByDateAndTime, [date, timeOfDay]),
            returnValue: _i3.Future<_i4.DailyCheckin?>.value(),
          )
          as _i3.Future<_i4.DailyCheckin?>);

  @override
  _i3.Future<void> deleteCheckin(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCheckin, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
