// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_drug_use_app/test/features/login/services/post_login_router_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter/material.dart' as _i1;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mobile_drug_use_app/services/app_lock_controller.dart' as _i4;
import 'package:mobile_drug_use_app/services/encryption_migration_service.dart'
    as _i7;
import 'package:mobile_drug_use_app/services/encryption_service_v2.dart'
    as _i10;
import 'package:mobile_drug_use_app/services/navigation_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i2;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>>
    extends _i2.SmartFake
    implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotifierProviderRef_1<T> extends _i2.SmartFake
    implements _i3.NotifierProviderRef<T> {
  _FakeNotifierProviderRef_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppLockState_2 extends _i2.SmartFake implements _i4.AppLockState {
  _FakeAppLockState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_3 extends _i2.SmartFake
    implements _i5.FunctionsClient {
  _FakeFunctionsClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_4 extends _i2.SmartFake
    implements _i5.SupabaseStorageClient {
  _FakeSupabaseStorageClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_5 extends _i2.SmartFake
    implements _i5.RealtimeClient {
  _FakeRealtimeClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_6 extends _i2.SmartFake
    implements _i5.PostgrestClient {
  _FakePostgrestClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_7 extends _i2.SmartFake implements _i5.GoTrueClient {
  _FakeGoTrueClient_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_8 extends _i2.SmartFake
    implements _i5.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_9 extends _i2.SmartFake
    implements _i5.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_10<T1> extends _i2.SmartFake
    implements _i5.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_11 extends _i2.SmartFake
    implements _i5.RealtimeChannel {
  _FakeRealtimeChannel_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_12 extends _i2.SmartFake
    implements _i5.GoTrueAdminApi {
  _FakeGoTrueAdminApi_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_13 extends _i2.SmartFake implements _i5.GoTrueMFAApi {
  _FakeGoTrueMFAApi_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_14 extends _i2.SmartFake implements _i5.AuthResponse {
  _FakeAuthResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_15 extends _i2.SmartFake implements _i5.OAuthResponse {
  _FakeOAuthResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_16 extends _i2.SmartFake
    implements _i5.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_17 extends _i2.SmartFake
    implements _i5.ResendResponse {
  _FakeResendResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_18 extends _i2.SmartFake implements _i5.UserResponse {
  _FakeUserResponse_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_19 extends _i2.SmartFake implements Object {
  _FakeObject_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i2.Mock implements _i6.NavigationService {
  MockNavigationService() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.GlobalKey<_i1.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_0<_i1.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i1.GlobalKey<_i1.NavigatorState>);

  @override
  void replace(String? route) => super.noSuchMethod(
    Invocation.method(#replace, [route]),
    returnValueForMissingStub: null,
  );

  @override
  void push(String? route) => super.noSuchMethod(
    Invocation.method(#push, [route]),
    returnValueForMissingStub: null,
  );

  @override
  void pop() => super.noSuchMethod(
    Invocation.method(#pop, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EncryptionMigrationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionMigrationService extends _i2.Mock
    implements _i7.EncryptionMigrationService {
  MockEncryptionMigrationService() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> needsMigration(String? uuidUserId) =>
      (super.noSuchMethod(
            Invocation.method(#needsMigration, [uuidUserId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String> migrateUserData(String? uuidUserId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#migrateUserData, [uuidUserId, pin]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#migrateUserData, [uuidUserId, pin]),
              ),
            ),
          )
          as _i8.Future<String>);
}

/// A class which mocks [EncryptionServiceV2].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionServiceV2 extends _i2.Mock
    implements _i10.EncryptionServiceV2 {
  MockEncryptionServiceV2() {
    _i2.throwOnMissingStub(this);
  }

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  _i8.Future<String> setupNewSecrets(String? uuidUserId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setupNewSecrets, [uuidUserId, pin]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#setupNewSecrets, [uuidUserId, pin]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<bool> unlockWithPin(String? uuidUserId, String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#unlockWithPin, [uuidUserId, pin]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> unlockWithRecoveryKey(
    String? uuidUserId,
    String? recoveryKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unlockWithRecoveryKey, [
              uuidUserId,
              recoveryKey,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> resetPinWithRecoveryKey(
    String? uuidUserId,
    String? recoveryKey,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPinWithRecoveryKey, [
              uuidUserId,
              recoveryKey,
              newPin,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> changePin(
    String? uuidUserId,
    String? oldPin,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePin, [uuidUserId, oldPin, newPin]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> enableBiometrics(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#enableBiometrics, [pin]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#disableBiometrics, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isBiometricsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricsEnabled, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> unlockWithBiometrics(String? uuidUserId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockWithBiometrics, [uuidUserId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String> encryptText(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encryptText, [plaintext]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#encryptText, [plaintext]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> decryptText(String? encryptedJson) =>
      (super.noSuchMethod(
            Invocation.method(#decryptText, [encryptedJson]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#decryptText, [encryptedJson]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  void lock() => super.noSuchMethod(
    Invocation.method(#lock, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> hasEncryptionSetup(String? uuidUserId) =>
      (super.noSuchMethod(
            Invocation.method(#hasEncryptionSetup, [uuidUserId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String?> encryptTextNullable(String? plaintext) =>
      (super.noSuchMethod(
            Invocation.method(#encryptTextNullable, [plaintext]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> decryptTextNullable(String? encryptedJson) =>
      (super.noSuchMethod(
            Invocation.method(#decryptTextNullable, [encryptedJson]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<Map<String, dynamic>> encryptFields(
    Map<String, dynamic>? data,
    List<String>? fieldsToEncrypt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#encryptFields, [data, fieldsToEncrypt]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> decryptFields(
    Map<String, dynamic>? data,
    List<String>? fieldsToDecrypt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptFields, [data, fieldsToDecrypt]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [AppLockController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLockController extends _i2.Mock implements _i4.AppLockController {
  MockAppLockController() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i3.NotifierProviderRef<_i4.AppLockState> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeNotifierProviderRef_1<_i4.AppLockState>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i3.NotifierProviderRef<_i4.AppLockState>);

  @override
  _i4.AppLockState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAppLockState_2(this, Invocation.getter(#state)),
          )
          as _i4.AppLockState);

  @override
  set state(_i4.AppLockState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.AppLockState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeAppLockState_2(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i4.AppLockState);

  @override
  _i8.Future<void> recordUnlock({DateTime? at}) =>
      (super.noSuchMethod(
            Invocation.method(#recordUnlock, [], {#at: at}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> onBackgroundStart({DateTime? at}) =>
      (super.noSuchMethod(
            Invocation.method(#onBackgroundStart, [], {#at: at}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> onForegroundResume({DateTime? now}) =>
      (super.noSuchMethod(
            Invocation.method(#onForegroundResume, [], {#now: now}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> shouldRequirePinNow() =>
      (super.noSuchMethod(
            Invocation.method(#shouldRequirePinNow, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void listenSelf(
    void Function(_i4.AppLockState?, _i4.AppLockState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i4.AppLockState? previous, _i4.AppLockState? next) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i2.Mock implements _i5.SupabaseClient {
  MockSupabaseClient() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_3(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i5.FunctionsClient);

  @override
  _i5.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_4(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.SupabaseStorageClient);

  @override
  _i5.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_5(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i5.RealtimeClient);

  @override
  _i5.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_6(this, Invocation.getter(#rest)),
          )
          as _i5.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i5.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_7(this, Invocation.getter(#auth)),
          )
          as _i5.GoTrueClient);

  @override
  set functions(_i5.FunctionsClient? _functions) => super.noSuchMethod(
    Invocation.setter(#functions, _functions),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i5.SupabaseStorageClient? _storage) => super.noSuchMethod(
    Invocation.setter(#storage, _storage),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i5.RealtimeClient? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i5.PostgrestClient? _rest) => super.noSuchMethod(
    Invocation.setter(#rest, _rest),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i5.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_8(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i5.SupabaseQueryBuilder);

  @override
  _i5.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_9(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i5.SupabaseQuerySchema);

  @override
  _i5.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_10<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i5.PostgrestFilterBuilder<T>);

  @override
  _i5.RealtimeChannel channel(
    String? name, {
    _i5.RealtimeChannelConfig? opts = const _i5.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_11(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i5.RealtimeChannel);

  @override
  List<_i5.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i5.RealtimeChannel>[],
          )
          as List<_i5.RealtimeChannel>);

  @override
  _i8.Future<String> removeChannel(_i5.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i2.Mock implements _i5.GoTrueClient {
  MockGoTrueClient() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_12(
              this,
              Invocation.getter(#admin),
            ),
          )
          as _i5.GoTrueAdminApi);

  @override
  _i5.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_13(this, Invocation.getter(#mfa)),
          )
          as _i5.GoTrueMFAApi);

  @override
  _i8.Stream<_i5.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i8.Stream<_i5.AuthState>.empty(),
          )
          as _i8.Stream<_i5.AuthState>);

  @override
  _i8.Stream<_i5.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i8.Stream<_i5.AuthState>.empty(),
          )
          as _i8.Stream<_i5.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i5.GoTrueAdminApi? _admin) => super.noSuchMethod(
    Invocation.setter(#admin, _admin),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i5.GoTrueMFAApi? _mfa) => super.noSuchMethod(
    Invocation.setter(#mfa, _mfa),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i5.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i5.OtpChannel? channel = _i5.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.OAuthResponse> getOAuthSignInUrl({
    required _i5.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i8.Future<_i5.OAuthResponse>.value(
              _FakeOAuthResponse_15(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.OAuthResponse>);

  @override
  _i8.Future<_i5.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i8.Future<_i5.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_16(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthSessionUrlResponse>);

  @override
  _i8.Future<_i5.AuthResponse> signInWithIdToken({
    required _i5.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i5.OtpChannel? channel = _i5.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i5.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i5.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.ResendResponse> resend({
    String? email,
    String? phone,
    required _i5.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i8.Future<_i5.ResendResponse>.value(
              _FakeResendResponse_17(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.ResendResponse>);

  @override
  _i8.Future<_i5.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i8.Future<_i5.UserResponse>.value(
              _FakeUserResponse_18(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i8.Future<_i5.UserResponse>);

  @override
  _i8.Future<_i5.UserResponse> updateUser(
    _i5.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i8.Future<_i5.UserResponse>.value(
              _FakeUserResponse_18(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.UserResponse>);

  @override
  _i8.Future<_i5.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [refreshToken]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#setSession, [refreshToken]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i8.Future<_i5.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_16(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.AuthSessionUrlResponse>);

  @override
  _i8.Future<void> signOut({
    _i5.SignOutScope? scope = _i5.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i5.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i8.Future<List<_i5.UserIdentity>>.value(
              <_i5.UserIdentity>[],
            ),
          )
          as _i8.Future<List<_i5.UserIdentity>>);

  @override
  _i8.Future<_i5.AuthResponse> linkIdentityWithIdToken({
    required _i5.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  _i8.Future<_i5.OAuthResponse> getLinkIdentityUrl(
    _i5.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i8.Future<_i5.OAuthResponse>.value(
              _FakeOAuthResponse_15(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i5.OAuthResponse>);

  @override
  _i8.Future<void> unlinkIdentity(_i5.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i8.Future<_i5.AuthResponse>.value(
              _FakeAuthResponse_14(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i8.Future<_i5.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i5.AuthChangeEvent? event, {
    _i5.Session? session,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_19(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i2.Mock implements _i5.User {
  MockUser() {
    _i2.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  Map<String, dynamic> get appMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#appMetadata),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  String get aud =>
      (super.noSuchMethod(
            Invocation.getter(#aud),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#aud)),
          )
          as String);

  @override
  String get createdAt =>
      (super.noSuchMethod(
            Invocation.getter(#createdAt),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#createdAt),
            ),
          )
          as String);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
