// MIGRATION:
// State: MODERN
// Navigation: GOROUTER
// Models: FREEZED
// Theme: COMPLETE
// Common: COMPLETE
// Notes: Tests for tolerance models

import 'package:flutter_test/flutter_test.dart';
import 'package:mobile_drug_use_app/features/tolerance/models/tolerance_models.dart';

void main() {
  group('Tolerance Models', () {
    test('UseLogEntry should be immutable and support equality', () {
      final now = DateTime.now();
      final entry1 = UseLogEntry(
        substanceSlug: 'caffeine',
        timestamp: now,
        doseUnits: 100,
      );
      final entry2 = UseLogEntry(
        substanceSlug: 'caffeine',
        timestamp: now,
        doseUnits: 100,
      );
      final entry3 = UseLogEntry(
        substanceSlug: 'alcohol',
        timestamp: now,
        doseUnits: 1,
      );

      expect(entry1, equals(entry2));
      expect(entry1, isNot(equals(entry3)));
    });

    test('ToleranceModel should parse from JSON correctly', () {
      final json = {
        'notes': 'Test notes',
        'neuro_buckets': {
          'stimulant': {'weight': 1.0, 'tolerance_type': 'stimulant'},
        },
        'half_life_hours': 5.0,
        'tolerance_decay_days': 3.0,
      };

      // Note: My Freezed model expects Map<String, NeuroBucket> for neuroBuckets.
      // But the JSON from Supabase has Map<String, Map<String, dynamic>>.
      // The Repository handles the conversion.
      // The ToleranceModel.fromJson generated by Freezed expects the structure defined in the class.
      // So I should test the class structure.

      final bucket = NeuroBucket(
        name: 'stimulant',
        weight: 1.0,
        toleranceType: 'stimulant',
      );
      final model = ToleranceModel(
        notes: 'Test notes',
        neuroBuckets: {'stimulant': bucket},
        halfLifeHours: 5.0,
        toleranceDecayDays: 3.0,
      );

      expect(model.notes, 'Test notes');
      expect(model.neuroBuckets['stimulant'], equals(bucket));
    });
  });
}
