// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_drug_use_app/test/features/tolerance/tolerance_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_drug_use_app/features/tolerance/controllers/tolerance_repository.dart'
    as _i2;
import 'package:mobile_drug_use_app/features/tolerance/models/tolerance_models.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ToleranceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockToleranceRepository extends _i1.Mock
    implements _i2.ToleranceRepository {
  MockToleranceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, _i4.ToleranceModel>> fetchToleranceModels() =>
      (super.noSuchMethod(
            Invocation.method(#fetchToleranceModels, []),
            returnValue: _i3.Future<Map<String, _i4.ToleranceModel>>.value(
              <String, _i4.ToleranceModel>{},
            ),
          )
          as _i3.Future<Map<String, _i4.ToleranceModel>>);

  @override
  _i3.Future<List<_i4.UseLogEntry>> fetchUseLogs({
    required String? userId,
    int? daysBack = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUseLogs, [], {
              #userId: userId,
              #daysBack: daysBack,
            }),
            returnValue: _i3.Future<List<_i4.UseLogEntry>>.value(
              <_i4.UseLogEntry>[],
            ),
          )
          as _i3.Future<List<_i4.UseLogEntry>>);
}
