// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_drug_use_app/test/widgets/log_entry/log_entry_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_drug_use_app/features/log_entry/log_entry_controller.dart'
    as _i2;
import 'package:mobile_drug_use_app/features/log_entry/models/log_entry_form_data.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValidationResult_0 extends _i1.SmartFake
    implements _i2.ValidationResult {
  _FakeValidationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveResult_1 extends _i1.SmartFake implements _i2.SaveResult {
  _FakeSaveResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogEntryController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogEntryController extends _i1.Mock
    implements _i2.LogEntryController {
  MockLogEntryController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> loadSubstanceDetails(
    String? substanceName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadSubstanceDetails, [substanceName]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  List<String> getAvailableROAs(Map<String, dynamic>? substanceDetails) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableROAs, [substanceDetails]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool isROAValidated(String? roa, Map<String, dynamic>? substanceDetails) =>
      (super.noSuchMethod(
            Invocation.method(#isROAValidated, [roa, substanceDetails]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<_i2.ValidationResult> validateSubstance(
    _i4.LogEntryFormData? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateSubstance, [data]),
            returnValue: _i3.Future<_i2.ValidationResult>.value(
              _FakeValidationResult_0(
                this,
                Invocation.method(#validateSubstance, [data]),
              ),
            ),
          )
          as _i3.Future<_i2.ValidationResult>);

  @override
  _i2.ValidationResult validateROA(_i4.LogEntryFormData? data) =>
      (super.noSuchMethod(
            Invocation.method(#validateROA, [data]),
            returnValue: _FakeValidationResult_0(
              this,
              Invocation.method(#validateROA, [data]),
            ),
          )
          as _i2.ValidationResult);

  @override
  _i2.ValidationResult validateEmotions(_i4.LogEntryFormData? data) =>
      (super.noSuchMethod(
            Invocation.method(#validateEmotions, [data]),
            returnValue: _FakeValidationResult_0(
              this,
              Invocation.method(#validateEmotions, [data]),
            ),
          )
          as _i2.ValidationResult);

  @override
  _i2.ValidationResult validateCraving(_i4.LogEntryFormData? data) =>
      (super.noSuchMethod(
            Invocation.method(#validateCraving, [data]),
            returnValue: _FakeValidationResult_0(
              this,
              Invocation.method(#validateCraving, [data]),
            ),
          )
          as _i2.ValidationResult);

  @override
  _i3.Future<_i2.SaveResult> saveLogEntry(_i4.LogEntryFormData? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveLogEntry, [data]),
            returnValue: _i3.Future<_i2.SaveResult>.value(
              _FakeSaveResult_1(this, Invocation.method(#saveLogEntry, [data])),
            ),
          )
          as _i3.Future<_i2.SaveResult>);
}
