// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_drug_use_app/test/features/login/login/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i5;
import 'package:mobile_drug_use_app/features/login/login/login_controller.dart'
    as _i3;
import 'package:mobile_drug_use_app/features/login/login/login_state.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginState_0 extends _i1.SmartFake implements _i2.LoginState {
  _FakeLoginState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginController].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginController extends _i1.Mock implements _i3.LoginController {
  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Stream<_i2.LoginState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.LoginState>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.LoginState>.empty(),
          )
          as _i4.Stream<_i2.LoginState>);

  @override
  _i2.LoginState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLoginState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeLoginState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.LoginState);

  @override
  _i2.LoginState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeLoginState_0(
              this,
              Invocation.getter(#debugState),
            ),
            returnValueForMissingStub: _FakeLoginState_0(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i2.LoginState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set onError(_i5.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i2.LoginState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  void init() => super.noSuchMethod(
    Invocation.method(#init, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> submitLogin({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitLogin, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void toggleRememberMe(bool? value) => super.noSuchMethod(
    Invocation.method(#toggleRememberMe, [value]),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i2.LoginState? old, _i2.LoginState? current) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.RemoveListener addListener(
    _i6.Listener<_i2.LoginState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i5.RemoveListener);
}
