// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_drug_use_app/test/features/login/login/login_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_drug_use_app/features/login/services/post_login_router.dart'
    as _i5;
import 'package:mobile_drug_use_app/features/login/services/auth_service.dart'
    as _i2;
import 'package:mobile_drug_use_app/core/services/onboarding_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_5 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_6 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_7 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_8<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_9 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueAdminApi_10 extends _i1.SmartFake
    implements _i3.GoTrueAdminApi {
  _FakeGoTrueAdminApi_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueMFAApi_11 extends _i1.SmartFake implements _i3.GoTrueMFAApi {
  _FakeGoTrueMFAApi_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_12 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOAuthResponse_13 extends _i1.SmartFake implements _i3.OAuthResponse {
  _FakeOAuthResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionUrlResponse_14 extends _i1.SmartFake
    implements _i3.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResendResponse_15 extends _i1.SmartFake
    implements _i3.ResendResponse {
  _FakeResendResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserResponse_16 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObject_17 extends _i1.SmartFake implements Object {
  _FakeObject_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_18<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSubscription_19<T1> extends _i1.SmartFake
    implements _i4.StreamSubscription<T1> {
  _FakeStreamSubscription_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.AuthResult> register({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PostLoginRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostLoginRouter extends _i1.Mock implements _i5.PostLoginRouter {
  MockPostLoginRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> routeAfterLogin({required bool? debug}) =>
      (super.noSuchMethod(
            Invocation.method(#routeAfterLogin, [], {#debug: debug}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void goToHome() => super.noSuchMethod(
    Invocation.method(#goToHome, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToLogin() => super.noSuchMethod(
    Invocation.method(#goToLogin, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToPinSetup() => super.noSuchMethod(
    Invocation.method(#goToPinSetup, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToPinUnlock() => super.noSuchMethod(
    Invocation.method(#goToPinUnlock, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToEncryptionMigration() => super.noSuchMethod(
    Invocation.method(#goToEncryptionMigration, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToOnboarding() => super.noSuchMethod(
    Invocation.method(#goToOnboarding, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnboardingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingService extends _i1.Mock implements _i6.OnboardingService {
  MockOnboardingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isOnboardingComplete() =>
      (super.noSuchMethod(
            Invocation.method(#isOnboardingComplete, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> completeOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#completeOnboarding, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#resetOnboarding, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isPrivacyPolicyAccepted() =>
      (super.noSuchMethod(
            Invocation.method(#isPrivacyPolicyAccepted, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> acceptPrivacyPolicy() =>
      (super.noSuchMethod(
            Invocation.method(#acceptPrivacyPolicy, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getUsageFrequency() =>
      (super.noSuchMethod(
            Invocation.method(#getUsageFrequency, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> saveUsageFrequency(String? frequencyId) =>
      (super.noSuchMethod(
            Invocation.method(#saveUsageFrequency, [frequencyId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isHarmNoticeDismissed(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#isHarmNoticeDismissed, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> dismissHarmNotice(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#dismissHarmNotice, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetHarmNotices() =>
      (super.noSuchMethod(
            Invocation.method(#resetHarmNotices, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_1(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i3.FunctionsClient);

  @override
  _i3.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_3(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i3.RealtimeClient);

  @override
  _i3.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_4(this, Invocation.getter(#rest)),
          )
          as _i3.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i3.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_5(this, Invocation.getter(#auth)),
          )
          as _i3.GoTrueClient);

  @override
  set functions(_i3.FunctionsClient? _functions) => super.noSuchMethod(
    Invocation.setter(#functions, _functions),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i3.SupabaseStorageClient? _storage) => super.noSuchMethod(
    Invocation.setter(#storage, _storage),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i3.RealtimeClient? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i3.PostgrestClient? _rest) => super.noSuchMethod(
    Invocation.setter(#rest, _rest),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i3.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_6(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_7(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_8<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_9(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i3.RealtimeChannel>[],
          )
          as List<_i3.RealtimeChannel>);

  @override
  _i4.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i3.GoTrueClient {
  MockGoTrueClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GoTrueAdminApi get admin =>
      (super.noSuchMethod(
            Invocation.getter(#admin),
            returnValue: _FakeGoTrueAdminApi_10(
              this,
              Invocation.getter(#admin),
            ),
          )
          as _i3.GoTrueAdminApi);

  @override
  _i3.GoTrueMFAApi get mfa =>
      (super.noSuchMethod(
            Invocation.getter(#mfa),
            returnValue: _FakeGoTrueMFAApi_11(this, Invocation.getter(#mfa)),
          )
          as _i3.GoTrueMFAApi);

  @override
  _i4.Stream<_i3.AuthState> get onAuthStateChange =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChange),
            returnValue: _i4.Stream<_i3.AuthState>.empty(),
          )
          as _i4.Stream<_i3.AuthState>);

  @override
  _i4.Stream<_i3.AuthState> get onAuthStateChangeSync =>
      (super.noSuchMethod(
            Invocation.getter(#onAuthStateChangeSync),
            returnValue: _i4.Stream<_i3.AuthState>.empty(),
          )
          as _i4.Stream<_i3.AuthState>);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  set admin(_i3.GoTrueAdminApi? _admin) => super.noSuchMethod(
    Invocation.setter(#admin, _admin),
    returnValueForMissingStub: null,
  );

  @override
  set mfa(_i3.GoTrueMFAApi? _mfa) => super.noSuchMethod(
    Invocation.setter(#mfa, _mfa),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i3.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, [], {
              #data: data,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInAnonymously, [], {
                  #data: data,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #emailRedirectTo: emailRedirectTo,
                  #data: data,
                  #captchaToken: captchaToken,
                  #channel: channel,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPassword, [], {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithPassword, [], {
                  #email: email,
                  #phone: phone,
                  #password: password,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.OAuthResponse> getOAuthSignInUrl({
    required _i3.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOAuthSignInUrl, [], {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            }),
            returnValue: _i4.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(#getOAuthSignInUrl, [], {
                  #provider: provider,
                  #redirectTo: redirectTo,
                  #scopes: scopes,
                  #queryParams: queryParams,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.OAuthResponse>);

  @override
  _i4.Future<_i3.AuthSessionUrlResponse> exchangeCodeForSession(
    String? authCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeCodeForSession, [authCode]),
            returnValue: _i4.Future<_i3.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_14(
                this,
                Invocation.method(#exchangeCodeForSession, [authCode]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i4.Future<_i3.AuthResponse> signInWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#signInWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithOtp, [], {
              #email: email,
              #phone: phone,
              #emailRedirectTo: emailRedirectTo,
              #shouldCreateUser: shouldCreateUser,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i3.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOTP, [], {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#verifyOTP, [], {
                  #email: email,
                  #phone: phone,
                  #token: token,
                  #type: type,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                  #tokenHash: tokenHash,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSSOSignInUrl, [], {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getSSOSignInUrl, [], {
                  #providerId: providerId,
                  #domain: domain,
                  #redirectTo: redirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i3.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshSession, [refreshToken]),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#refreshSession, [refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<void> reauthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.ResendResponse> resend({
    String? email,
    String? phone,
    required _i3.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resend, [], {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.ResendResponse>.value(
              _FakeResendResponse_15(
                this,
                Invocation.method(#resend, [], {
                  #email: email,
                  #phone: phone,
                  #type: type,
                  #emailRedirectTo: emailRedirectTo,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.ResendResponse>);

  @override
  _i4.Future<_i3.UserResponse> getUser([String? jwt]) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [jwt]),
            returnValue: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(this, Invocation.method(#getUser, [jwt])),
            ),
          )
          as _i4.Future<_i3.UserResponse>);

  @override
  _i4.Future<_i3.UserResponse> updateUser(
    _i3.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUser,
              [attributes],
              {#emailRedirectTo: emailRedirectTo},
            ),
            returnValue: _i4.Future<_i3.UserResponse>.value(
              _FakeUserResponse_16(
                this,
                Invocation.method(
                  #updateUser,
                  [attributes],
                  {#emailRedirectTo: emailRedirectTo},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.UserResponse>);

  @override
  _i4.Future<_i3.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [refreshToken]),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#setSession, [refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSessionFromUrl,
              [originUrl],
              {#storeSession: storeSession},
            ),
            returnValue: _i4.Future<_i3.AuthSessionUrlResponse>.value(
              _FakeAuthSessionUrlResponse_14(
                this,
                Invocation.method(
                  #getSessionFromUrl,
                  [originUrl],
                  {#storeSession: storeSession},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i4.Future<void> signOut({
    _i3.SignOutScope? scope = _i3.SignOutScope.local,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#scope: scope}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resetPasswordForEmail,
              [email],
              {#redirectTo: redirectTo, #captchaToken: captchaToken},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i3.UserIdentity>> getUserIdentities() =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentities, []),
            returnValue: _i4.Future<List<_i3.UserIdentity>>.value(
              <_i3.UserIdentity>[],
            ),
          )
          as _i4.Future<List<_i3.UserIdentity>>);

  @override
  _i4.Future<_i3.AuthResponse> linkIdentityWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkIdentityWithIdToken, [], {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            }),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#linkIdentityWithIdToken, [], {
                  #provider: provider,
                  #idToken: idToken,
                  #accessToken: accessToken,
                  #nonce: nonce,
                  #captchaToken: captchaToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  _i4.Future<_i3.OAuthResponse> getLinkIdentityUrl(
    _i3.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getLinkIdentityUrl,
              [provider],
              {
                #redirectTo: redirectTo,
                #scopes: scopes,
                #queryParams: queryParams,
              },
            ),
            returnValue: _i4.Future<_i3.OAuthResponse>.value(
              _FakeOAuthResponse_13(
                this,
                Invocation.method(
                  #getLinkIdentityUrl,
                  [provider],
                  {
                    #redirectTo: redirectTo,
                    #scopes: scopes,
                    #queryParams: queryParams,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i3.OAuthResponse>);

  @override
  _i4.Future<void> unlinkIdentity(_i3.UserIdentity? identity) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkIdentity, [identity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setInitialSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#setInitialSession, [jsonStr]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
            Invocation.method(#recoverSession, [jsonStr]),
            returnValue: _i4.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_12(
                this,
                Invocation.method(#recoverSession, [jsonStr]),
              ),
            ),
          )
          as _i4.Future<_i3.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
    Invocation.method(#startAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
    Invocation.method(#stopAutoRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyAllSubscribers(
    _i3.AuthChangeEvent? event, {
    _i3.Session? session,
    bool? broadcast = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #notifyAllSubscribers,
      [event],
      {#session: session, #broadcast: broadcast},
    ),
    returnValueForMissingStub: null,
  );

  @override
  Object notifyException(Object? exception, [StackTrace? stackTrace]) =>
      (super.noSuchMethod(
            Invocation.method(#notifyException, [exception, stackTrace]),
            returnValue: _FakeObject_17(
              this,
              Invocation.method(#notifyException, [exception, stackTrace]),
            ),
          )
          as Object);
}

/// A class which mocks [Stream].
///
/// See the documentation for Mockito's code generation for more information.
class MockStream<T> extends _i1.Mock implements _i4.Stream<T> {
  MockStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(Invocation.getter(#isBroadcast), returnValue: false)
          as bool);

  @override
  _i4.Future<int> get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<T> get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(this, Invocation.getter(#first)),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(this, Invocation.getter(#first)),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(this, Invocation.getter(#last)),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(this, Invocation.getter(#last)),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(this, Invocation.getter(#single)),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(this, Invocation.getter(#single)),
          )
          as _i4.Future<T>);

  @override
  _i4.Stream<T> asBroadcastStream({
    void Function(_i4.StreamSubscription<T>)? onListen,
    void Function(_i4.StreamSubscription<T>)? onCancel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#asBroadcastStream, [], {
              #onListen: onListen,
              #onCancel: onCancel,
            }),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.StreamSubscription<T> listen(
    void Function(T)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [onData],
              {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError,
              },
            ),
            returnValue: _FakeStreamSubscription_19<T>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
          )
          as _i4.StreamSubscription<T>);

  @override
  _i4.Stream<T> where(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<S> map<S>(S Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#map, [convert]),
            returnValue: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Stream<E> asyncMap<E>(_i4.FutureOr<E> Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncMap, [convert]),
            returnValue: _i4.Stream<E>.empty(),
          )
          as _i4.Stream<E>);

  @override
  _i4.Stream<E> asyncExpand<E>(_i4.Stream<E>? Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncExpand, [convert]),
            returnValue: _i4.Stream<E>.empty(),
          )
          as _i4.Stream<E>);

  @override
  _i4.Stream<T> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [onError], {#test: test}),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<S> expand<S>(Iterable<S> Function(T)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [convert]),
            returnValue: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Future<dynamic> pipe(_i4.StreamConsumer<T>? streamConsumer) =>
      (super.noSuchMethod(
            Invocation.method(#pipe, [streamConsumer]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Stream<S> transform<S>(_i4.StreamTransformer<T, S>? streamTransformer) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [streamTransformer]),
            returnValue: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Future<T> reduce(T Function(T, T)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#reduce, [combine]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#reduce, [combine]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(this, Invocation.method(#reduce, [combine])),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<S> fold<S>(S? initialValue, S Function(S, T)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i4.Future<S>.value(v),
                ) ??
                _FakeFuture_18<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
          )
          as _i4.Future<S>);

  @override
  _i4.Future<String> join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [needle]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> forEach(void Function(T)? action) =>
      (super.noSuchMethod(
            Invocation.method(#forEach, [action]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> every(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(#every, [test]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> any(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(#any, [test]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<R> cast<R>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Future<List<T>> toList() =>
      (super.noSuchMethod(
            Invocation.method(#toList, []),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<Set<T>> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: _i4.Future<Set<T>>.value(<T>{}),
          )
          as _i4.Future<Set<T>>);

  @override
  _i4.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(#drain, [futureValue]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i4.Future<E>.value(v),
                ) ??
                _FakeFuture_18<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
          )
          as _i4.Future<E>);

  @override
  _i4.Stream<T> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<T> takeWhile(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<T> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<T> skipWhile(bool Function(T)? test) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Stream<T> distinct([bool Function(T, T)? equals]) =>
      (super.noSuchMethod(
            Invocation.method(#distinct, [equals]),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  _i4.Future<T> firstWhere(bool Function(T)? test, {T Function()? orElse}) =>
      (super.noSuchMethod(
            Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#firstWhere, [test], {#orElse: orElse}),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(#firstWhere, [test], {#orElse: orElse}),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> lastWhere(bool Function(T)? test, {T Function()? orElse}) =>
      (super.noSuchMethod(
            Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#lastWhere, [test], {#orElse: orElse}),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(#lastWhere, [test], {#orElse: orElse}),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> singleWhere(bool Function(T)? test, {T Function()? orElse}) =>
      (super.noSuchMethod(
            Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#singleWhere, [test], {#orElse: orElse}),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(#singleWhere, [test], {#orElse: orElse}),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<T> elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#elementAt, [index]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#elementAt, [index]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(this, Invocation.method(#elementAt, [index])),
          )
          as _i4.Future<T>);

  @override
  _i4.Stream<T> timeout(
    Duration? timeLimit, {
    void Function(_i4.EventSink<T>)? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);
}
