// // Mocks generated by Mockito 5.4.6 from annotations
// // in mobile_drug_use_app/test/integration/log_entry_save_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i8;

// import 'package:functions_client/functions_client.dart' as _i3;
// import 'package:gotrue/gotrue.dart' as _i2;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i10;
// import 'package:postgrest/postgrest.dart' as _i6;
// import 'package:realtime_client/realtime_client.dart' as _i5;
// import 'package:storage_client/storage_client.dart' as _i4;
// import 'package:supabase/src/supabase_client.dart' as _i9;
// import 'package:supabase/src/supabase_query_builder.dart' as _i7;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class
// // ignore_for_file: invalid_use_of_internal_member

// class _FakeGoTrueClient_0 extends _i1.SmartFake implements _i2.GoTrueClient {
//   _FakeGoTrueClient_0(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeFunctionsClient_1 extends _i1.SmartFake
//     implements _i3.FunctionsClient {
//   _FakeFunctionsClient_1(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
//     implements _i4.SupabaseStorageClient {
//   _FakeSupabaseStorageClient_2(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeRealtimeClient_3 extends _i1.SmartFake
//     implements _i5.RealtimeClient {
//   _FakeRealtimeClient_3(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakePostgrestClient_4 extends _i1.SmartFake
//     implements _i6.PostgrestClient {
//   _FakePostgrestClient_4(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeSupabaseQueryBuilder_5 extends _i1.SmartFake
//     implements _i7.SupabaseQueryBuilder {
//   _FakeSupabaseQueryBuilder_5(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakePostgrestFilterBuilder_6<T> extends _i1.SmartFake
//     implements _i6.PostgrestFilterBuilder<T> {
//   _FakePostgrestFilterBuilder_6(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeRealtimeChannel_7 extends _i1.SmartFake
//     implements _i5.RealtimeChannel {
//   _FakeRealtimeChannel_7(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakePostgrestBuilder_8<T1, S> extends _i1.SmartFake
//     implements _i6.PostgrestBuilder<T1, S> {
//   _FakePostgrestBuilder_8(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakePostgrestResponse_9<T1> extends _i1.SmartFake
//     implements _i6.PostgrestResponse<T1> {
//   _FakePostgrestResponse_9(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// class _FakeFuture_10<T1> extends _i1.SmartFake implements _i8.Future<T1> {
//   _FakeFuture_10(Object parent, Invocation parentInvocation)
//     : super(parent, parentInvocation);
// }

// /// A class which mocks [SupabaseClient].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockSupabaseClient extends _i1.Mock implements _i9.SupabaseClient {
//   MockSupabaseClient() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   String get supabaseUrl =>
//       (super.noSuchMethod(
//             Invocation.getter(#supabaseUrl),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#supabaseUrl),
//             ),
//           )
//           as String);

//   @override
//   String get supabaseKey =>
//       (super.noSuchMethod(
//             Invocation.getter(#supabaseKey),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#supabaseKey),
//             ),
//           )
//           as String);

//   @override
//   String get schema =>
//       (super.noSuchMethod(
//             Invocation.getter(#schema),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#schema),
//             ),
//           )
//           as String);

//   @override
//   String get restUrl =>
//       (super.noSuchMethod(
//             Invocation.getter(#restUrl),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#restUrl),
//             ),
//           )
//           as String);

//   @override
//   String get realtimeUrl =>
//       (super.noSuchMethod(
//             Invocation.getter(#realtimeUrl),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#realtimeUrl),
//             ),
//           )
//           as String);

//   @override
//   String get authUrl =>
//       (super.noSuchMethod(
//             Invocation.getter(#authUrl),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#authUrl),
//             ),
//           )
//           as String);

//   @override
//   String get storageUrl =>
//       (super.noSuchMethod(
//             Invocation.getter(#storageUrl),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#storageUrl),
//             ),
//           )
//           as String);

//   @override
//   String get functionsUrl =>
//       (super.noSuchMethod(
//             Invocation.getter(#functionsUrl),
//             returnValue: _i10.dummyValue<String>(
//               this,
//               Invocation.getter(#functionsUrl),
//             ),
//           )
//           as String);

//   @override
//   _i2.GoTrueClient get auth =>
//       (super.noSuchMethod(
//             Invocation.getter(#auth),
//             returnValue: _FakeGoTrueClient_0(this, Invocation.getter(#auth)),
//           )
//           as _i2.GoTrueClient);

//   @override
//   _i3.FunctionsClient get functions =>
//       (super.noSuchMethod(
//             Invocation.getter(#functions),
//             returnValue: _FakeFunctionsClient_1(
//               this,
//               Invocation.getter(#functions),
//             ),
//           )
//           as _i3.FunctionsClient);

//   @override
//   _i4.SupabaseStorageClient get storage =>
//       (super.noSuchMethod(
//             Invocation.getter(#storage),
//             returnValue: _FakeSupabaseStorageClient_2(
//               this,
//               Invocation.getter(#storage),
//             ),
//           )
//           as _i4.SupabaseStorageClient);

//   @override
//   _i5.RealtimeClient get realtime =>
//       (super.noSuchMethod(
//             Invocation.getter(#realtime),
//             returnValue: _FakeRealtimeClient_3(
//               this,
//               Invocation.getter(#realtime),
//             ),
//           )
//           as _i5.RealtimeClient);

//   @override
//   _i6.PostgrestClient get rest =>
//       (super.noSuchMethod(
//             Invocation.getter(#rest),
//             returnValue: _FakePostgrestClient_4(this, Invocation.getter(#rest)),
//           )
//           as _i6.PostgrestClient);

//   @override
//   Map<String, String> get headers =>
//       (super.noSuchMethod(
//             Invocation.getter(#headers),
//             returnValue: <String, String>{},
//           )
//           as Map<String, String>);

//   @override
//   set auth(_i2.GoTrueClient? value) => super.noSuchMethod(
//     Invocation.setter(#auth, value),
//     returnValueForMissingStub: null,
//   );

//   @override
//   set functions(_i3.FunctionsClient? value) => super.noSuchMethod(
//     Invocation.setter(#functions, value),
//     returnValueForMissingStub: null,
//   );

//   @override
//   set storage(_i4.SupabaseStorageClient? value) => super.noSuchMethod(
//     Invocation.setter(#storage, value),
//     returnValueForMissingStub: null,
//   );

//   @override
//   set realtime(_i5.RealtimeClient? value) => super.noSuchMethod(
//     Invocation.setter(#realtime, value),
//     returnValueForMissingStub: null,
//   );

//   @override
//   set rest(_i6.PostgrestClient? value) => super.noSuchMethod(
//     Invocation.setter(#rest, value),
//     returnValueForMissingStub: null,
//   );

//   @override
//   set headers(Map<String, String>? headers) => super.noSuchMethod(
//     Invocation.setter(#headers, headers),
//     returnValueForMissingStub: null,
//   );

//   @override
//   _i7.SupabaseQueryBuilder from(String? table) =>
//       (super.noSuchMethod(
//             Invocation.method(#from, [table]),
//             returnValue: _FakeSupabaseQueryBuilder_5(
//               this,
//               Invocation.method(#from, [table]),
//             ),
//           )
//           as _i7.SupabaseQueryBuilder);

//   @override
//   _i6.PostgrestClient useSchema(String? schema) =>
//       (super.noSuchMethod(
//             Invocation.method(#useSchema, [schema]),
//             returnValue: _FakePostgrestClient_4(
//               this,
//               Invocation.method(#useSchema, [schema]),
//             ),
//           )
//           as _i6.PostgrestClient);

//   @override
//   _i6.PostgrestFilterBuilder<dynamic> rpc(
//     String? fn, {
//     Map<String, dynamic>? params,
//     _i6.FetchOptions? options = const _i6.FetchOptions(),
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#rpc, [fn], {#params: params, #options: options}),
//             returnValue: _FakePostgrestFilterBuilder_6<dynamic>(
//               this,
//               Invocation.method(
//                 #rpc,
//                 [fn],
//                 {#params: params, #options: options},
//               ),
//             ),
//           )
//           as _i6.PostgrestFilterBuilder<dynamic>);

//   @override
//   _i5.RealtimeChannel channel(
//     String? name, {
//     _i5.RealtimeChannelConfig? opts = const _i5.RealtimeChannelConfig(),
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#channel, [name], {#opts: opts}),
//             returnValue: _FakeRealtimeChannel_7(
//               this,
//               Invocation.method(#channel, [name], {#opts: opts}),
//             ),
//           )
//           as _i5.RealtimeChannel);

//   @override
//   List<_i5.RealtimeChannel> getChannels() =>
//       (super.noSuchMethod(
//             Invocation.method(#getChannels, []),
//             returnValue: <_i5.RealtimeChannel>[],
//           )
//           as List<_i5.RealtimeChannel>);

//   @override
//   _i8.Future<String> removeChannel(_i5.RealtimeChannel? channel) =>
//       (super.noSuchMethod(
//             Invocation.method(#removeChannel, [channel]),
//             returnValue: _i8.Future<String>.value(
//               _i10.dummyValue<String>(
//                 this,
//                 Invocation.method(#removeChannel, [channel]),
//               ),
//             ),
//           )
//           as _i8.Future<String>);

//   @override
//   _i8.Future<List<String>> removeAllChannels() =>
//       (super.noSuchMethod(
//             Invocation.method(#removeAllChannels, []),
//             returnValue: _i8.Future<List<String>>.value(<String>[]),
//           )
//           as _i8.Future<List<String>>);

//   @override
//   _i8.Future<void> dispose() =>
//       (super.noSuchMethod(
//             Invocation.method(#dispose, []),
//             returnValue: _i8.Future<void>.value(),
//             returnValueForMissingStub: _i8.Future<void>.value(),
//           )
//           as _i8.Future<void>);
// }

// /// A class which mocks [PostgrestQueryBuilder].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockPostgrestQueryBuilder<T> extends _i1.Mock
//     implements _i6.PostgrestQueryBuilder<T> {
//   MockPostgrestQueryBuilder() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i6.PostgrestFilterBuilder<R> select<R>([
//     String? columns = '*',
//     _i6.FetchOptions? options = const _i6.FetchOptions(),
//   ]) =>
//       (super.noSuchMethod(
//             Invocation.method(#select, [columns, options]),
//             returnValue: _FakePostgrestFilterBuilder_6<R>(
//               this,
//               Invocation.method(#select, [columns, options]),
//             ),
//           )
//           as _i6.PostgrestFilterBuilder<R>);

//   @override
//   _i6.PostgrestFilterBuilder<T> insert(
//     dynamic values, {
//     bool? defaultToNull = true,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(
//               #insert,
//               [values],
//               {#defaultToNull: defaultToNull},
//             ),
//             returnValue: _FakePostgrestFilterBuilder_6<T>(
//               this,
//               Invocation.method(
//                 #insert,
//                 [values],
//                 {#defaultToNull: defaultToNull},
//               ),
//             ),
//           )
//           as _i6.PostgrestFilterBuilder<T>);

//   @override
//   _i6.PostgrestFilterBuilder<T> upsert(
//     dynamic values, {
//     String? onConflict,
//     bool? ignoreDuplicates = false,
//     bool? defaultToNull = true,
//     _i6.FetchOptions? options = const _i6.FetchOptions(),
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(
//               #upsert,
//               [values],
//               {
//                 #onConflict: onConflict,
//                 #ignoreDuplicates: ignoreDuplicates,
//                 #defaultToNull: defaultToNull,
//                 #options: options,
//               },
//             ),
//             returnValue: _FakePostgrestFilterBuilder_6<T>(
//               this,
//               Invocation.method(
//                 #upsert,
//                 [values],
//                 {
//                   #onConflict: onConflict,
//                   #ignoreDuplicates: ignoreDuplicates,
//                   #defaultToNull: defaultToNull,
//                   #options: options,
//                 },
//               ),
//             ),
//           )
//           as _i6.PostgrestFilterBuilder<T>);

//   @override
//   _i6.PostgrestFilterBuilder<T> update(
//     Map<dynamic, dynamic>? values, {
//     _i6.FetchOptions? options = const _i6.FetchOptions(),
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#update, [values], {#options: options}),
//             returnValue: _FakePostgrestFilterBuilder_6<T>(
//               this,
//               Invocation.method(#update, [values], {#options: options}),
//             ),
//           )
//           as _i6.PostgrestFilterBuilder<T>);

//   @override
//   _i6.PostgrestFilterBuilder<T> delete({
//     _i6.ReturningOption? returning = _i6.ReturningOption.representation,
//     _i6.FetchOptions? options = const _i6.FetchOptions(),
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#delete, [], {
//               #returning: returning,
//               #options: options,
//             }),
//             returnValue: _FakePostgrestFilterBuilder_6<T>(
//               this,
//               Invocation.method(#delete, [], {
//                 #returning: returning,
//                 #options: options,
//               }),
//             ),
//           )
//           as _i6.PostgrestFilterBuilder<T>);

//   @override
//   _i6.PostgrestBuilder<R, T> withConverter<R>(
//     _i6.PostgrestConverter<R, T>? converter,
//   ) =>
//       (super.noSuchMethod(
//             Invocation.method(#withConverter, [converter]),
//             returnValue: _FakePostgrestBuilder_8<R, T>(
//               this,
//               Invocation.method(#withConverter, [converter]),
//             ),
//           )
//           as _i6.PostgrestBuilder<R, T>);

//   @override
//   _i8.Future<_i6.PostgrestResponse<dynamic>> execute({
//     bool? head = false,
//     _i6.CountOption? count,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#execute, [], {#head: head, #count: count}),
//             returnValue: _i8.Future<_i6.PostgrestResponse<dynamic>>.value(
//               _FakePostgrestResponse_9<dynamic>(
//                 this,
//                 Invocation.method(#execute, [], {#head: head, #count: count}),
//               ),
//             ),
//           )
//           as _i8.Future<_i6.PostgrestResponse<dynamic>>);

//   @override
//   void appendSearchParams(String? key, String? value) => super.noSuchMethod(
//     Invocation.method(#appendSearchParams, [key, value]),
//     returnValueForMissingStub: null,
//   );

//   @override
//   void overrideSearchParams(String? key, String? value) => super.noSuchMethod(
//     Invocation.method(#overrideSearchParams, [key, value]),
//     returnValueForMissingStub: null,
//   );

//   @override
//   _i8.Stream<T> asStream() =>
//       (super.noSuchMethod(
//             Invocation.method(#asStream, []),
//             returnValue: _i8.Stream<T>.empty(),
//           )
//           as _i8.Stream<T>);

//   @override
//   _i8.Future<T> catchError(Function? onError, {bool Function(Object)? test}) =>
//       (super.noSuchMethod(
//             Invocation.method(#catchError, [onError], {#test: test}),
//             returnValue:
//                 _i10.ifNotNull(
//                   _i10.dummyValueOrNull<T>(
//                     this,
//                     Invocation.method(#catchError, [onError], {#test: test}),
//                   ),
//                   (T v) => _i8.Future<T>.value(v),
//                 ) ??
//                 _FakeFuture_10<T>(
//                   this,
//                   Invocation.method(#catchError, [onError], {#test: test}),
//                 ),
//           )
//           as _i8.Future<T>);

//   @override
//   _i8.Future<R> then<R>(
//     _i8.FutureOr<R> Function(T)? onValue, {
//     Function? onError,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#then, [onValue], {#onError: onError}),
//             returnValue:
//                 _i10.ifNotNull(
//                   _i10.dummyValueOrNull<R>(
//                     this,
//                     Invocation.method(#then, [onValue], {#onError: onError}),
//                   ),
//                   (R v) => _i8.Future<R>.value(v),
//                 ) ??
//                 _FakeFuture_10<R>(
//                   this,
//                   Invocation.method(#then, [onValue], {#onError: onError}),
//                 ),
//           )
//           as _i8.Future<R>);

//   @override
//   _i8.Future<T> timeout(
//     Duration? timeLimit, {
//     _i8.FutureOr<T> Function()? onTimeout,
//   }) =>
//       (super.noSuchMethod(
//             Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
//             returnValue:
//                 _i10.ifNotNull(
//                   _i10.dummyValueOrNull<T>(
//                     this,
//                     Invocation.method(
//                       #timeout,
//                       [timeLimit],
//                       {#onTimeout: onTimeout},
//                     ),
//                   ),
//                   (T v) => _i8.Future<T>.value(v),
//                 ) ??
//                 _FakeFuture_10<T>(
//                   this,
//                   Invocation.method(
//                     #timeout,
//                     [timeLimit],
//                     {#onTimeout: onTimeout},
//                   ),
//                 ),
//           )
//           as _i8.Future<T>);

//   @override
//   _i8.Future<T> whenComplete(_i8.FutureOr<void> Function()? action) =>
//       (super.noSuchMethod(
//             Invocation.method(#whenComplete, [action]),
//             returnValue:
//                 _i10.ifNotNull(
//                   _i10.dummyValueOrNull<T>(
//                     this,
//                     Invocation.method(#whenComplete, [action]),
//                   ),
//                   (T v) => _i8.Future<T>.value(v),
//                 ) ??
//                 _FakeFuture_10<T>(
//                   this,
//                   Invocation.method(#whenComplete, [action]),
//                 ),
//           )
//           as _i8.Future<T>);
// }
